/**
 * Harvester cert runner (Fase 2, CB-018). Runs the validated beta harvester
 * through its cert gates on the cached Blofin 3y daily data and writes the
 * canonical results doc. The 2018-2026 OOS validation lives separately in
 * probe-beta-oos.ts; this is the in-sample cert of the production module
 * (src/strategy/harvester.ts).
 */

import { promises as fs } from "node:fs";
import { fetchBars } from "./lib/bulk-fetch.js";
import {
  simulateHarvester,
  harvesterStats,
  certify,
  DEFAULT_HARVESTER_CONFIG,
  DEFAULT_CERT_GATES,
  type AssetSeries,
  type HarvesterStats,
} from "../src/strategy/harvester.js";
import type { Candle } from "../src/analysis/indicators.js";

const DAY_MS = 86_400_000;
const WINDOW_DAYS = 1095;
const TO_MS = Math.floor(Date.now() / DAY_MS) * DAY_MS;
const FROM_MS = TO_MS - WINDOW_DAYS * DAY_MS;

const BTC_ONLY = ["BTC-USDT"];
const BASKET = ["BTC-USDT", "ETH-USDT", "SOL-USDT", "BNB-USDT"];

async function load(symbols: string[]): Promise<AssetSeries[]> {
  const out: AssetSeries[] = [];
  for (const s of symbols) {
    const candles: Candle[] = await fetchBars(s, "1D", FROM_MS, TO_MS);
    if (candles.length > 0) out.push({ symbol: s, candles });
  }
  return out;
}

/** Stats over the warmup-trimmed portion of a harvester run. */
function statsOf(series: AssetSeries[]): { stats: HarvesterStats; turnover: number } {
  const res = simulateHarvester(series, DEFAULT_HARVESTER_CONFIG);
  const k = res.warmupEndIndex;
  const stats = harvesterStats(res.dailyReturns.slice(k), res.days.slice(k), res.turnoverByDay.slice(k));
  return { stats, turnover: stats.meanTurnover };
}

/** Buy-hold benchmark over the same trimmed window as a harvester run. */
function buyHold(btc: AssetSeries, warmupDays: number): HarvesterStats {
  const days = btc.candles.map((c) => c.t);
  const rets: number[] = [];
  const stamps: number[] = [];
  for (let i = 1; i < btc.candles.length; i++) {
    rets.push(btc.candles[i]!.c / btc.candles[i - 1]!.c - 1);
    stamps.push(btc.candles[i]!.t);
  }
  return harvesterStats(rets.slice(warmupDays), stamps.slice(warmupDays), []);
}

console.log(`window ${new Date(FROM_MS).toISOString().slice(0, 10)} → ${new Date(TO_MS).toISOString().slice(0, 10)}\n`);

const btcSeries = await load(BTC_ONLY);
const basketSeries = await load(BASKET);
const warmup = Math.max(DEFAULT_HARVESTER_CONFIG.volLookbackDays, DEFAULT_HARVESTER_CONFIG.regimeMaPeriodDays) + 1;

const btcRun = statsOf(btcSeries);
const basketRun = statsOf(basketSeries);
const bench = buyHold(btcSeries[0]!, warmup);

const btcCert = certify(btcRun.stats, bench);
const basketCert = certify(basketRun.stats, bench);

function fmt(s: HarvesterStats): string {
  return `Sharpe=${s.sharpe.toFixed(2)}  CAGR=${(s.cagr * 100).toFixed(0)}%  annVol=${(s.annVol * 100).toFixed(0)}%  maxDD=${(s.maxDD * 100).toFixed(0)}%  turn/d=${(s.meanTurnover * 100).toFixed(1)}%`;
}

console.log(`BENCHMARK buy-hold BTC:  ${fmt(bench)}`);
console.log(`\nBTC-only harvester:      ${fmt(btcRun.stats)}  → ${btcCert.pass ? "CERTIFIED" : "FAIL"}`);
for (const c of btcCert.checks) console.log(`   [${c.pass ? "P" : "."}] ${c.name}: ${c.detail}`);
console.log(`\nBasket harvester (${BASKET.length}):   ${fmt(basketRun.stats)}  → ${basketCert.pass ? "CERTIFIED" : "FAIL"}`);
for (const c of basketCert.checks) console.log(`   [${c.pass ? "P" : "."}] ${c.name}: ${c.detail}`);

const byYearTable = (s: HarvesterStats) => s.byYear.map((y) => `${y.year}: ${(y.ret * 100).toFixed(0)}%`).join("  ");

const doc = `# Harvester backtest results (Fase 2 cert)

Generated by \`scripts/harvester-backtest.ts\` from \`src/strategy/harvester.ts\`.
In-sample window: ${new Date(FROM_MS).toISOString().slice(0, 10)} → ${new Date(TO_MS).toISOString().slice(0, 10)} (Blofin daily, warmup ${warmup}d trimmed).
Out-of-sample 2018-2026 validation: \`docs/CRYPTOTRADER_BUILD_PLAN.md\` §15 + \`probe-beta-oos.ts\`.

Config: vol-lookback ${DEFAULT_HARVESTER_CONFIG.volLookbackDays}d, MA regime ${DEFAULT_HARVESTER_CONFIG.regimeMaPeriodDays}d, target vol ${(DEFAULT_HARVESTER_CONFIG.targetAnnualVol * 100).toFixed(0)}%, max gross ${DEFAULT_HARVESTER_CONFIG.maxGross}, rebalance ${DEFAULT_HARVESTER_CONFIG.rebalanceEveryDays}d, cost ${(DEFAULT_HARVESTER_CONFIG.costPerLegRoundTrip * 10000).toFixed(0)}bps/leg.

Required cert gates (risk-adjusted): Sharpe ≥ ${DEFAULT_CERT_GATES.minSharpe}, maxDD < ${(DEFAULT_CERT_GATES.maxMaxDD * 100).toFixed(0)}%, maxDD < benchmark, worst year ≥ ${(DEFAULT_CERT_GATES.worstYearFloor * 100).toFixed(0)}%.
Informational (NOT gating): raw CAGR vs benchmark — a risk-managed overlay trails raw buy-hold in bull-heavy windows by design and wins over full cycles via drawdown avoidance (Gate-B lesson, §15). This 2023-2026 window is bull-heavy, so the harvester trailing buy-hold CAGR here is expected; the full-cycle judgement on raw return is the 2018-2026 OOS run (§15: 9.23x vs 4.77x).

| Variant | Sharpe | CAGR | annVol | maxDD | turn/d | Verdict |
|---|---|---|---|---|---|---|
| Buy-hold BTC (benchmark) | ${bench.sharpe.toFixed(2)} | ${(bench.cagr * 100).toFixed(0)}% | ${(bench.annVol * 100).toFixed(0)}% | ${(bench.maxDD * 100).toFixed(0)}% | — | — |
| BTC-only harvester | ${btcRun.stats.sharpe.toFixed(2)} | ${(btcRun.stats.cagr * 100).toFixed(0)}% | ${(btcRun.stats.annVol * 100).toFixed(0)}% | ${(btcRun.stats.maxDD * 100).toFixed(0)}% | ${(btcRun.stats.meanTurnover * 100).toFixed(1)}% | ${btcCert.pass ? "CERTIFIED" : "FAIL"} |
| Basket harvester (${BASKET.join(", ")}) | ${basketRun.stats.sharpe.toFixed(2)} | ${(basketRun.stats.cagr * 100).toFixed(0)}% | ${(basketRun.stats.annVol * 100).toFixed(0)}% | ${(basketRun.stats.maxDD * 100).toFixed(0)}% | ${(basketRun.stats.meanTurnover * 100).toFixed(1)}% | ${basketCert.pass ? "CERTIFIED" : "FAIL"} |

Per-year returns:
- Buy-hold BTC: ${byYearTable(bench)}
- BTC harvester: ${byYearTable(btcRun.stats)}
- Basket harvester: ${byYearTable(basketRun.stats)}

Note: in-sample Sharpe overlaps the period the params were chosen on; the
honest evidence is the OOS run. This doc certifies the production module
reproduces the validated behavior end-to-end.
`;

await fs.writeFile("docs/HARVESTER_BACKTEST_RESULTS.md", doc);
console.log(`\nresults doc written → docs/HARVESTER_BACKTEST_RESULTS.md`);
console.log(`\nFASE-2 CERT: ${btcCert.pass || basketCert.pass ? "PASS — production module reproduces validated behavior" : "FAIL — investigate before proceeding"}`);
